version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: talento_escucha_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: talento_escucha_db
      POSTGRES_USER: talento_user
      POSTGRES_PASSWORD: talento_password_2024
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - talento_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U talento_user -d talento_escucha_db"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  adminer:
    image: adminer:latest
    container_name: talento_escucha_adminer
    restart: unless-stopped
    ports:
      - "8081:8080"
    networks:
      - talento_network
    depends_on:
      - postgres
    environment:
      ADMINER_DEFAULT_SERVER: postgres

volumes:
  postgres_data:
    driver: local

networks:
  talento_network:
    driver: bridge
