# Generated by Django 5.2.1 on 2025-09-23 23:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del solicitante', max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(help_text='Apellido del solicitante', max_length=100, verbose_name='Apellido')),
                ('correo', models.EmailField(help_text='Email de contacto del solicitante', max_length=254, verbose_name='Correo Electrónico')),
                ('agencia', models.CharField(blank=True, help_text='Nombre de la agencia o empresa', max_length=200, null=True, verbose_name='Agencia')),
                ('telefono', models.CharField(blank=True, help_text='Número de teléfono de contacto', max_length=20, null=True, verbose_name='Teléfono')),
                ('tipo_solicitud', models.CharField(choices=[('coaching', 'Coaching Profesional'), ('capacitacion', 'Capacitación Empresarial'), ('evaluacion', 'Evaluación de Talento'), ('consulta', 'Consulta General'), ('soporte', 'Soporte Técnico'), ('otro', 'Otro')], help_text='Categoría de la solicitud', max_length=50, verbose_name='Tipo de Solicitud')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del ticket', verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última actualización', verbose_name='Fecha de Actualización')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('resuelto', 'Resuelto'), ('cerrado', 'Cerrado'), ('cancelado', 'Cancelado')], default='pendiente', help_text='Estado actual del ticket', max_length=20, verbose_name='Estado')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada de la solicitud', null=True, verbose_name='Descripción')),
                ('notas_internas', models.TextField(blank=True, help_text='Notas internas para el equipo', null=True, verbose_name='Notas Internas')),
                ('usuario_actualiza', models.ForeignKey(blank=True, help_text='Usuario que realizó la última actualización', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tickets_actualizados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que Actualiza')),
                ('usuario_asignado', models.ForeignKey(blank=True, help_text='Usuario responsable de atender el ticket', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_asignados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Asignado')),
                ('usuario_crea', models.ForeignKey(blank=True, help_text='Usuario que creó el ticket', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tickets_creados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que Crea')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
                'db_table': 'tickets_ticket',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='TicketAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operacion', models.CharField(choices=[('CREATE', 'Creación'), ('UPDATE', 'Actualización'), ('DELETE', 'Eliminación')], help_text='Tipo de operación realizada', max_length=10, verbose_name='Operación')),
                ('datos_anteriores', models.JSONField(blank=True, help_text='Estado del ticket antes del cambio', null=True, verbose_name='Datos Anteriores')),
                ('datos_nuevos', models.JSONField(blank=True, help_text='Estado del ticket después del cambio', null=True, verbose_name='Datos Nuevos')),
                ('campos_modificados', models.JSONField(blank=True, help_text='Lista de campos que fueron modificados', null=True, verbose_name='Campos Modificados')),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora cuando se realizó la operación', verbose_name='Fecha del Cambio')),
                ('ip_usuario', models.GenericIPAddressField(blank=True, help_text='Dirección IP desde donde se realizó el cambio', null=True, verbose_name='IP del Usuario')),
                ('comentario', models.TextField(blank=True, help_text='Comentario adicional sobre el cambio realizado', null=True, verbose_name='Comentario')),
                ('ticket', models.ForeignKey(help_text='Ticket al que pertenece esta auditoría', on_delete=django.db.models.deletion.CASCADE, related_name='auditorias', to='tickets.ticket', verbose_name='Ticket')),
                ('usuario', models.ForeignKey(blank=True, help_text='Usuario que realizó la operación', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Auditoría de Ticket',
                'verbose_name_plural': 'Auditorías de Tickets',
                'db_table': 'tickets_ticket_auditoria',
                'ordering': ['-fecha_cambio'],
            },
        ),
    ]
