# Generated by Django 5.2.1 on 2025-09-24 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='tipo_solicitud',
            field=models.CharField(choices=[('P', 'Peticiones'), ('Q', 'Quejas'), ('R', 'Reclamos'), ('S', 'Solicitudes')], help_text='Categoría de la solicitud', max_length=50, verbose_name='Tipo de Solicitud'),
        ),
    ]
