# Generated by Django 5.2.1 on 2025-09-24 03:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def create_default_agencia(apps, schema_editor):
    """Crear agencia por defecto"""
    Agencia = apps.get_model('tickets', 'Agencia')
    User = apps.get_model('auth', 'User')
    
    # Crear un usuario admin si no existe
    admin_user, created = User.objects.get_or_create(
        username='admin',
        defaults={
            'email': 'admin@talento-escucha.com',
            'is_staff': True,
            'is_superuser': True
        }
    )
    
    # Crear agencia por defecto
    default_agencia, created = Agencia.objects.get_or_create(
        codigo_faces='DEFAULT001',
        defaults={
            'nombre': 'Agencia General',
            'usuario_creacion': admin_user,
            'usuario_actualizacion': admin_user
        }
    )


def reverse_default_agencia(apps, schema_editor):
    """Eliminar agencia por defecto"""
    Agencia = apps.get_model('tickets', 'Agencia')
    Agencia.objects.filter(codigo_faces='DEFAULT001').delete()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0002_update_tipo_solicitud_choices'),
    ]

    operations = [
        # Crear modelo Agencia
        migrations.CreateModel(
            name='Agencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_faces', models.CharField(help_text='Código único de identificación FACES', max_length=50, unique=True, verbose_name='Código FACES')),
                ('nombre', models.CharField(help_text='Nombre completo de la empresa o agencia', max_length=200, verbose_name='Nombre de la Agencia')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro', verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última actualización', verbose_name='Fecha de Actualización')),
                ('usuario_actualizacion', models.ForeignKey(help_text='Usuario que actualizó por última vez esta agencia', on_delete=django.db.models.deletion.PROTECT, related_name='agencias_actualizadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario de Actualización')),
                ('usuario_creacion', models.ForeignKey(help_text='Usuario que creó esta agencia', on_delete=django.db.models.deletion.PROTECT, related_name='agencias_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario de Creación')),
            ],
            options={
                'verbose_name': 'Agencia',
                'verbose_name_plural': 'Agencias',
                'ordering': ['nombre'],
            },
        ),
        
        # Crear agencia por defecto
        migrations.RunPython(create_default_agencia, reverse_default_agencia),
    ]
