# Generated by Django 5.2.1 on 2025-09-24 03:58

from django.db import migrations, models
import django.db.models.deletion


def update_existing_tickets(apps, schema_editor):
    """Actualizar tickets existentes con agencia por defecto"""
    Ticket = apps.get_model('tickets', 'Ticket')
    Agencia = apps.get_model('tickets', 'Agencia')
    
    # Obtener la agencia por defecto
    default_agencia = Agencia.objects.get(codigo_faces='DEFAULT001')
    
    # Actualizar todos los tickets existentes
    for ticket in Ticket.objects.all():
        ticket.agencia_temp = default_agencia
        ticket.save()


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_add_agencia_model'),
    ]

    operations = [
        # Agregar campo temporal para la nueva referencia
        migrations.AddField(
            model_name='ticket',
            name='agencia_temp',
            field=models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.PROTECT, to='tickets.agencia', related_name='tickets_temp'),
        ),
        
        # Poblar el campo temporal
        migrations.RunPython(update_existing_tickets, migrations.RunPython.noop),
        
        # Eliminar el campo original
        migrations.RemoveField(
            model_name='ticket',
            name='agencia',
        ),
        
        # Renombrar el campo temporal
        migrations.RenameField(
            model_name='ticket',
            old_name='agencia_temp',
            new_name='agencia',
        ),
        
        # Hacer los campos requeridos
        migrations.AlterField(
            model_name='ticket',
            name='telefono',
            field=models.CharField(help_text='Número de teléfono de contacto', max_length=20, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='descripcion',
            field=models.TextField(help_text='Descripción detallada de la solicitud', verbose_name='Descripción'),
        ),
        
        # Hacer agencia requerida
        migrations.AlterField(
            model_name='ticket',
            name='agencia',
            field=models.ForeignKey(help_text='Agencia o empresa asociada al ticket', on_delete=django.db.models.deletion.PROTECT, to='tickets.agencia', verbose_name='Agencia'),
        ),
    ]