# Generated by Django 5.2.1 on 2025-09-24 04:36

from django.conf import settings
from django.db import migrations, models


def populate_codigo_field(apps, schema_editor):
    """Poblar el campo codigo para tickets existentes"""
    Ticket = apps.get_model('tickets', 'Ticket')
    
    for ticket in Ticket.objects.all():
        ticket.codigo = f"FAC{ticket.id}"
        ticket.save(update_fields=['codigo'])


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_update_ticket_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Agregar campo sin unique constraint
        migrations.AddField(
            model_name='ticket',
            name='codigo',
            field=models.CharField(blank=True, help_text='Código único del ticket (FAC + ID)', max_length=20, verbose_name='Código'),
        ),
        
        # Poblar códigos existentes
        migrations.RunPython(populate_codigo_field, migrations.RunPython.noop),
        
        # Ahora agregar la restricción unique
        migrations.AlterField(
            model_name='ticket',
            name='codigo',
            field=models.CharField(blank=True, help_text='Código único del ticket (FAC + ID)', max_length=20, unique=True, verbose_name='Código'),
        ),
        migrations.AddIndex(
            model_name='agencia',
            index=models.Index(fields=['codigo_faces'], name='tickets_age_codigo__f8fc45_idx'),
        ),
        migrations.AddIndex(
            model_name='agencia',
            index=models.Index(fields=['nombre'], name='tickets_age_nombre_58bd50_idx'),
        ),
    ]
