# Generated by Django 5.2.1 on 2025-09-24 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_ticket_codigo_agencia_tickets_age_codigo__f8fc45_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='severidad',
            field=models.CharField(choices=[('A', 'Alto'), ('M', 'Medio'), ('B', 'Bajo')], default='M', help_text='Nivel de severidad del ticket', max_length=1, verbose_name='Severidad'),
        ),
    ]
