# Generated by Django 5.2.1 on 2025-09-25 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_ticket_severidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='solucion',
            field=models.TextField(blank=True, help_text='Descripción de la solución implementada', null=True, verbose_name='Solución'),
        ),
    ]
