# Generated by Django 5.2.1 on 2025-09-25 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_ticket_solucion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='notas_internas',
        ),
    ]
