# Generated by Django 5.2.1 on 2025-09-25 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_remove_notas_internas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketauditoria',
            name='operacion',
            field=models.CharField(choices=[('CREATE', 'Creación'), ('ASSIGN', 'Asignación'), ('RESOLVE', 'Resolución'), ('UPDATE', 'Actualización'), ('DELETE', 'Eliminación')], help_text='Tipo de operación realizada', max_length=20, verbose_name='Operación'),
        ),
    ]
