# Generated by Django 5.2.1 on 2025-09-26 05:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_update_auditoria_operacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='agencia',
            name='provincia',
            field=models.CharField(blank=True, help_text='Provincia donde se ubica la agencia', max_length=100, null=True, verbose_name='Provincia'),
        ),
        migrations.AddIndex(
            model_name='agencia',
            index=models.Index(fields=['provincia'], name='tickets_age_provinc_6f0891_idx'),
        ),
    ]
