# Generated by Django 5.2.1 on 2026-03-25 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0011_ticket_motivo_rechazo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketauditoria',
            name='operacion',
            field=models.CharField(choices=[('CREATE', 'Creación'), ('ASSIGN', 'Asignación'), ('REJECT', 'Rechazo'), ('RESOLVE', 'Resolución'), ('UPDATE', 'Actualización'), ('DELETE', 'Eliminación')], help_text='Tipo de operación realizada', max_length=20, verbose_name='Operación'),
        ),
    ]
